version: '3.8'
services:
  app:
    image: 'app'
    container_name: 'app'
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=Vanitha1405_
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - MYAPP_WIREMOCK=http://wiremock:8080
    ports:
          - "8080:8080"

  db:
    image: 'postgres:alpine'
    container_name: 'db'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Vanitha1405_

  wiremock:
    image: 'wiremock/wiremock'
    container_name: 'wiremock'
    ports:
      - "8082:8080"
    command: "--global-response-templating --verbose"
    volumes:
      - ./wiremock-files:/home/wiremock/__files
      - ./wiremock-mappings:/home/wiremock/mappings

